### ISSUE TITLE
JRE 8 support

### ISSUE THREAD

**Issue by quequiere** [Jannyboy11/GuiLib#5] opened 2019-12-15 20:38 UTC
Hello,
Lot of people run minecraft server on java 8.0 version.
Could you please compile a version for JAVA 8 ? Some servers can't be updated.

Thank you =)

**Comment by Jannyboy11** [comment] 2019-12-28 18:45
No. I don't intend to support any version of Java lower than the latest long-term support release, which is currently Java 11. Java is backwards compatible meaning that server owners can just upgrade their Java. Spigot will still work as well as all installed plugins. Plugins that reflect into other classes illegaly might require special privileges, which you can grant via commandline options. I use the following startup command for my test server: `java -enableassertions --illegal-access=permit --add-opens=java.base/java.lang=ALL-UNNAMED --enable-preview -jar -DIReallyKnowWhatIAmDoingISwear spigot-1.15.1.jar`, that is on Java 13.

I'm closing this issue as a duplicate of #2.

**Closed as completed by Jannyboy11** 2019-12-28 18:45 UTC
